
services:

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "443:443"
    depends_on:
      - auth-service
      - chat-service
      - user-management-service
      - game-service
      - frontend
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    build:
      services/auth-service
    volumes:
      - ./services/auth-service/data:/app/data
      - /app/node_modules
    networks:
      - app-network
    env_file: ".env"

  chat-service:
    container_name: chat-service
    build:
      services/chat-service
    volumes:
      - ./services/chat-service/data:/app/data
      - /app/node_modules
    networks:
      - app-network
    env_file: ".env"

  game-service:
    container_name: game-service
    build:
      services/game-service
    volumes:
      - ./services/game-service/data:/app/data
      - /app/node_modules
    networks:
      - app-network
    env_file: ".env"


  user-management-service:
    container_name: user-management-service
    build:
      services/user-management-service
    volumes:
      - /app/node_modules
      - ./services/user-management-service/data:/app/data
    networks:
      - app-network
    env_file: ".env"

  frontend:
    container_name: frontend
    build:
      ./frontend
    command: dev
    networks:
      - app-network
    depends_on:
      - auth-service
      - chat-service
      - user-management-service
      - game-service
    env_file: ".env"


networks:
  app-network:
    driver: bridge

