
services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - frontend
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    build:
      services/auth-service
    volumes:
      - ./services/auth-service/data:/app/data
    networks:
      - app-network

  chat-service:
    container_name: chat-service
    build:
      services/chat-service
    volumes:
      - ./services/chat-service/data:/app/data
    networks:
      - app-network

  game-service:
    container_name: game-service
    build:
      services/game-service
    volumes:
      - ./services/game-service/data:/app/data
    networks:
      - app-network

  tournament-service:
    container_name: tournament-service
    build:
      services/tournament-service
    volumes:
      - ./services/tournament-service/data:/app/data
    networks:
      - app-network

  user-management-service:
    container_name: user-management-service
    build:
      services/user-management-service
    volumes:
      - ./services/user-management-service/data:/app/data
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      ./frontend
    command: dev
    ports:
      - "5173:5173"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

